/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 快速開始',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: '01-quickstart' },
      ],
    },
    {
      type: 'category',
      label: '🏗️ 概念與架構',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: '02-concepts' },
      ],
    },
    {
      type: 'category',
      label: '🔗 整合開發實戰',
      link: { type: 'generated-index' },
      items: [
        'integration/rest-api-auth',
        'integration/rest-api-crud-wo',
      ],
    },
    {
      type: 'category',
      label: '🤖 自動化與配置',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: '05-automation' },
      ],
    },
    {
      type: 'category',
      label: '📋 新手顧問專區',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: '06-functional' },
      ],
    },
    {
      type: 'category',
      label: '🛡️ 維運與安全',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: '07-operations' },
      ],
    },
  ],
};

module.exports = sidebars;
